### ISSUE TITLE
连接服务器失败啊，172.16.16.90 这个IP应该怎么改？改成哪一个？

### ISSUE THREAD

**Issue by CordyHo** [kgxl/AndroidWebrtcDemo#1]

**Comment by CordyHo** [comment]
局域网的，windows环境，nodejs也安装了，也在cmd上面允许了server文件夹里的js文件，跑APP就提示连接服务器失败
android studio打印这个：connectFailure-->io.socket.engineio.client.EngineIOException: xhr poll error

**Comment by kgxl** [comment]
> EngineIOException

改成你本地的socket的ip就好了
